### ISSUE TITLE
Can we have a release tag?

### ISSUE THREAD

**Issue by t-lo** [vincent-petithory/dataurl#7]
Hi @vincent-petithory ,

Reaching out because one of our OS components - [Ignition](https://github.com/flatcar-linux/ignition) - uses your great work; and the [origin project](https://github.com/coreos/ignition) of or component does, too.

We'd like to reference the module with a release tag, which we feel is a cleaner way to integrate the library. Would it be possible to create a tag / release in this project for ease of use?

Also, should you be interested in our help with maintaining this module, we'd make ourselves available, too.

(CC: @bgilbert from the coreos ignition project)

**Comment by vincent-petithory** [comment]
Hello @t-lo,

I added a v1.0.0 tag just now.

**Comment by t-lo** [comment]
Thank you very much @vincent-petithory! This resolves our issue.
Also, if you'd like us to help with maintenance at any point in time, just let us know!

**Comment by sergeevabc** [comment]
# Problem

Cannot build from sources using either `go install` or `go build`.

``` console
$ git clone https://github.com/vincent-petithory/dataurl.git

$ cd dataurl/cmd/dataurl

$ go build
go: cannot find main module, but found .git/config in C:\Go\bin\dataurl
        to create a module there, run:
        cd ..\.. && go mod init

$ cd .. & cd .. & go modinit
go: cannot determine module path for source directory C:\Go\bin\dataurl (outside GOPATH, module path must be specified)
```

# Solution

It looks like the project has been moved to another repository.

``` console
$ go install -ldflags="-s -w" github.com/SterlynLee/dataurl/cmd/dataurl@latest
...

$ dataurl
dataurl - Encode or decode dataurl data and print to standard output

Usage: dataurl [OPTION]... [FILE]
...
```
